(function(){"use strict";var reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;var fine=window.matchMedia("(hover: hover) and (pointer: fine)").matches;var wide=window.matchMedia("(min-width: 901px)");var $=function(s,c){return(c||document).querySelector(s);};var $$=function(s,c){return Array.prototype.slice.call((c||document).querySelectorAll(s));};var clamp=function(v,a,b){return v<a?a:v>b?b:v;};var openTargets=$$("[data-pf-open]");var liveTargets=$$("[data-pf-live]");if("IntersectionObserver"in window){var openIO=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){e.target.classList.add("is-open");openIO.unobserve(e.target);}});},{threshold:0.22,rootMargin:"0px 0px -8% 0px"});openTargets.forEach(function(el){openIO.observe(el);});var liveIO=new IntersectionObserver(function(entries){entries.forEach(function(e){e.target.classList.toggle("is-live",e.isIntersecting);});},{threshold:0.05});liveTargets.forEach(function(el){liveIO.observe(el);});}else{openTargets.forEach(function(el){el.classList.add("is-open");});liveTargets.forEach(function(el){el.classList.add("is-live");});}
var overture=$(".pf-overture");if(overture){requestAnimationFrame(function(){overture.classList.add("is-open");});}
var YT_ID="R1O0VanJfTo";var players=$$("[data-pf-player]");function warmYouTube(){if(document.getElementById("pf-yt-pre"))return;["https://www.youtube-nocookie.com","https://www.youtube.com"].forEach(function(o){var l=document.createElement("link");l.id="pf-yt-pre";l.rel="preconnect";l.href=o;l.crossOrigin="anonymous";document.head.appendChild(l);});}
function mountPlayer(host,autoplay){var id=host.getAttribute("data-yt")||YT_ID;var frame=document.createElement("iframe");frame.className="pf-player__frame";frame.title=host.getAttribute("data-yt-title")||"Portfolio reel — Abhijeet Varghese";frame.src="https://www.youtube-nocookie.com/embed/"+id+"?rel=0&modestbranding=1&playsinline=1&hl=en&autoplay="+(autoplay?1:0);frame.setAttribute("allow","accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share");frame.setAttribute("allowfullscreen","true");frame.setAttribute("referrerpolicy","strict-origin-when-cross-origin");frame.loading="lazy";host.innerHTML="";host.appendChild(frame);host.classList.add("is-playing");if(autoplay){try{frame.focus();}catch(err){}}}
players.forEach(function(host){var poster=$(".pf-player__poster",host);if(!poster){return;}
poster.addEventListener("click",function(){warmYouTube();mountPlayer(host,true);});});var film=$(".pf-film");if(film&&"IntersectionObserver"in window){var warmIO=new IntersectionObserver(function(entries){if(entries[0].isIntersecting){warmYouTube();warmIO.disconnect();}},{rootMargin:"600px 0px"});warmIO.observe(film);}
var filmFrame=$(".pf-film__frame");var seam=$(".pf-seam");var ticking=false;function measure(){ticking=false;var vh=window.innerHeight;if(filmFrame&&!reduced){var fr=filmFrame.getBoundingClientRect();var gate=vh*0.45;var exit=clamp((gate-fr.bottom)/gate,0,1);filmFrame.style.setProperty("--exit",exit.toFixed(3));}
if(seam&&!reduced){var sr=seam.getBoundingClientRect();var p=clamp((vh-sr.top)/(vh+sr.height),0,1);var o=clamp(p/0.22,0,1)*clamp((1-p)/0.28,0,1);seam.style.setProperty("--p",p.toFixed(4));seam.style.setProperty("--o",o.toFixed(3));seam.style.setProperty("--o2",clamp((p-0.42)/0.25,0,1).toFixed(3));}}
function onScroll(){if(ticking){return;}
ticking=true;requestAnimationFrame(measure);}
if(filmFrame||seam){window.addEventListener("scroll",onScroll,{passive:true});window.addEventListener("resize",onScroll,{passive:true});measure();}
if(fine&&!reduced){var cursor=$(".pf-cursor");var cursorLabel=cursor&&$(".pf-cursor span",cursor);if(cursor&&cursorLabel){var tx=0,ty=0,cx=0,cy=0,raf=null,moving=false;function loop(){cx+=(tx-cx)*0.18;cy+=(ty-cy)*0.18;cursor.style.transform="translate3d("+cx.toFixed(1)+"px,"+cy.toFixed(1)+"px,0)";if(Math.abs(tx-cx)>0.1||Math.abs(ty-cy)>0.1){raf=requestAnimationFrame(loop);}else{raf=null;moving=false;}}
document.addEventListener("pointermove",function(e){if(e.pointerType!=="mouse"){return;}
tx=e.clientX;ty=e.clientY;if(!moving){moving=true;raf=requestAnimationFrame(loop);}},{passive:true});document.addEventListener("pointerover",function(e){var target=e.target&&e.target.closest?e.target.closest("[data-cursor]"):null;if(!target){return;}
cursorLabel.textContent=target.getAttribute("data-cursor")||"";cursor.classList.add("is-on","is-big");document.body.classList.add("pf-cursor-active");});document.addEventListener("pointerout",function(e){var from=e.target&&e.target.closest?e.target.closest("[data-cursor]"):null;if(!from){return;}
var to=e.relatedTarget&&e.relatedTarget.closest?e.relatedTarget.closest("[data-cursor]"):null;if(to===from){return;}
cursor.classList.remove("is-on","is-big");document.body.classList.remove("pf-cursor-active");});window.addEventListener("blur",function(){cursor.classList.remove("is-on","is-big");document.body.classList.remove("pf-cursor-active");});}}})();(function(){var rail=document.getElementById("pfProofRail");if(!rail){return;}
var panels=Array.prototype.slice.call(rail.querySelectorAll(".r-proof__panel"));var cur=document.getElementById("pfProofCur");var prev=document.getElementById("pfProofPrev");var next=document.getElementById("pfProofNext");var progress=document.getElementById("pfProofProgress");var reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;if(!panels.length){return;}
var active=0;var sync=function(i){active=i;panels.forEach(function(p,k){p.classList.toggle("is-active",k===i);});if(cur){cur.textContent=String(i+1).padStart(2,"0");}
if(prev){prev.disabled=i===0;}
if(next){next.disabled=i===panels.length-1;}};var update=function(){var mid=rail.scrollLeft+rail.clientWidth/2;var best=0;panels.forEach(function(p,i){if(mid>=p.offsetLeft){best=i;}});sync(best);if(progress){var max=rail.scrollWidth-rail.clientWidth;var rl=rail.scrollLeft;progress.style.width=(max>0?(rl/max)*100:0).toFixed(2)+"%";}};var go=function(i){var el=panels[i];if(!el){return;}
rail.scrollTo({left:el.offsetLeft,behavior:reduced?"auto":"smooth"});};rail.addEventListener("scroll",update,{passive:true});window.addEventListener("resize",update,{passive:true});if(prev)prev.addEventListener("click",function(){go(Math.max(0,active-1));});if(next)next.addEventListener("click",function(){go(Math.min(panels.length-1,active+1));});rail.addEventListener("keydown",function(e){if(e.key==="ArrowRight"){e.preventDefault();go(Math.min(panels.length-1,active+1));}
else if(e.key==="ArrowLeft"){e.preventDefault();go(Math.max(0,active-1));}});update();})();