const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  await page.goto('http://127.0.0.1:8092/story.html?as4=1', { waitUntil: 'domcontentloaded' });
  await page.waitForTimeout(2600);
  const shot = async (name, y) => {
    await page.evaluate(y => window.scrollTo(0, y), y);
    await page.waitForTimeout(900);
    await page.screenshot({ path: `/home/user/previews/min-${name}.png` });
  };
  await shot('01-hero', 0);
  await shot('02-spread', 900);
  await shot('03-facts-credo-zoom', 1900);
  await shot('04-frame-motion', 3300);
  await shot('05-frame-interaction', 4000);
  await shot('06-frame-env', 4700);
  await shot('07-frame-system', 5400);
  await shot('08-frame-people', 6100);
  await shot('09-frame-leadership', 6800);
  await shot('10-what', 9500);
  await shot('11-now', 10600);
  await shot('12-curious-credits', 11500);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.waitForTimeout(1000);
  await page.screenshot({ path: '/home/user/previews/min-m1-hero.png' });
  await page.evaluate(() => window.scrollTo(0, 3300));
  await page.waitForTimeout(1000);
  await page.screenshot({ path: '/home/user/previews/min-m2-frame.png' });
  await browser.close();
  console.log('MIN SHOTS DONE');
})();
