const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  await page.goto('http://127.0.0.1:8092/story.html?as4=1', { waitUntil: 'domcontentloaded' });
  await page.waitForTimeout(2800);
  const shot = async (name, y) => {
    await page.evaluate(y => window.scrollTo(0, y), y);
    await page.waitForTimeout(900);
    await page.screenshot({ path: `/home/user/previews/story-r3f-${name}.png` });
  };
  await shot('01-theater', 0);
  await shot('02-spread', 900);
  await shot('03-stats-zoom', 3350);
  await shot('04-reel-row', 4350);
  await page.evaluate(() => {
    const t = document.querySelector('.about-act__trigger[aria-controls="aboutActPanel-03"]');
    if (t.getAttribute('aria-expanded') !== 'true') t.click();
  });
  await page.waitForTimeout(1500);
  await shot('05-chapter-env', 5200);
  await page.evaluate(() => document.querySelector('.about-act__trigger[aria-controls="aboutActPanel-04"]').click());
  await page.waitForTimeout(1500);
  await shot('06-system', 6600);
  await page.evaluate(() => document.querySelector('.about-act__trigger[aria-controls="aboutActPanel-06"]').click());
  await page.waitForTimeout(1500);
  await shot('07-leadership', 9000);
  await shot('08-interludes', 7600);
  await shot('09-credits', 12200);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.waitForTimeout(1200);
  await page.screenshot({ path: '/home/user/previews/story-r3f-m1-theater.png' });
  await page.evaluate(() => window.scrollTo(0, 1500));
  await page.waitForTimeout(1000);
  await page.screenshot({ path: '/home/user/previews/story-r3f-m2-spread.png' });
  await page.evaluate(() => window.scrollTo(0, 4300));
  await page.waitForTimeout(1000);
  await page.screenshot({ path: '/home/user/previews/story-r3f-m3-reel.png' });
  await browser.close();
  console.log('FINAL SHOTS DONE');
})();
